# Permalinks
permalink:           pretty

# Setup
title:               Abdulhamit Çelik
tagline:             Software Engineer.
url:                 https://hmtcelik.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Abdulhamit Çelik
  url:               https://twitter.com/abdulhamitcelk
  email:             abhmtcelik@gmail.com

# Custom vars
twitter:             abdulhamitcelk
github:              hmtcelik

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
